name: Manifest

on:
  pull_request_target:
    paths:
      - 'west.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  contribs:
    runs-on: ubuntu-latest
    name: Manifest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          path: ncs/nrf
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Manifest
        uses: oyvindronningstad/action-manifest@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          manifest-path: 'west.yml'
          checkout-path: 'ncs/nrf'
          label-prefix: 'manifest-'
          verbosity-level: '1'
          labels: 'manifest,\
                  CI-all-test:zephyr;nrfxlib,\
                  CI-tfm-test:trusted-firmware-m;tfm-mcuboot,\
                  CI-boot-dfu-test:mcuboot;mcumgr,\
                  CI-matter-test:matter,\
                  CI-find-my-test:find-my,\
                  CI-homekit-test:homekit,\
                  CI-thread-test:openthread,\
                  CI-crypto-test:mbedtls;mbedtls-nrf'
          dnm-labels: 'DNM'
